# Generated by Django 5.0.6 on 2024-05-13 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('registration', models.PositiveIntegerField()),
                ('birthDate', models.DateField()),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('entryDate', models.DateField()),
                ('course', models.CharField(max_length=20)),
            ],
        ),
    ]
